language: objective-c

osx_image: xcode7.3

before_install:
   - rvm use system
   - sudo gem install bundler
   - sudo gem install cocoapods -v '0.39.0'

script: 
   xcodebuild -workspace SwiftPaginationCoreDataExample.xcworkspace -scheme SwiftPaginationCoreDataExample build -sdk iphonesimulator
